<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="1.079" timestamp="2025-01-31T13:50:55.335683" hostname="kirtiman-Latitude-3420"><testcase classname="tests.tests_channel_service.tests_event_row_alerts.test_event_row_alerts.TestRowAlert" name="test_event_row_live_alerts[Live-Alert.unknown-source]" time="0.007"><error message="failed on setup with &quot;Failed: Unable to load config data. Aborting tests.&quot;">@pytest.fixture(scope="session")
    def config_data():
        try:
            config_file_name = os.environ.get("config")
            logger.info(f"Config file name: {config_file_name}")
    
&gt;           with open(config_file_name, "r") as config_file:
E           TypeError: expected str, bytes or os.PathLike object, not NoneType

../../../conftest.py:32: TypeError

During handling of the above exception, another exception occurred:

    @pytest.fixture(scope="session")
    def config_data():
        try:
            config_file_name = os.environ.get("config")
            logger.info(f"Config file name: {config_file_name}")
    
            with open(config_file_name, "r") as config_file:
                config_data = yaml.safe_load(config_file)
                logger.info(f"Loaded config file info: {config_data}")
                return config_data
        except Exception as e:
            logger.error(f"Error loading config file: {str(e)}")
&gt;           pytest.fail("Unable to load config data. Aborting tests.")
E           Failed: Unable to load config data. Aborting tests.

../../../conftest.py:38: Failed</error></testcase></testsuite></testsuites>